keys: 
  - &host_desktop age1p7nc6skmfyn0wx4fs6e99x278r2ymcpnylq0utyzaegkz65lqymqyw7eem
  - &server age1h73ltq23vf5ruq07cpu9vn66cmt8mcga2lccqccg3sku20ru5vkqvqj0mv

creation_rules:
  - path_regex: Secret/[^/]+\.(yaml|ttf)$
    key_groups: 
    - age: 
      - *host_desktop
      - *server

